

name: DotnetTest

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches: 
      - main
      - development
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Cleanup
        run: dotnet clean
